// MapLibre GL Mock for Jest tests
const maplibreGl = {
  Map: jest.fn().mockImplementation(() => ({
    on: jest.fn(),
    off: jest.fn(),
    once: jest.fn(),
    remove: jest.fn(),
    addControl: jest.fn(),
    removeControl: jest.fn(),
    addSource: jest.fn(),
    removeSource: jest.fn(),
    addLayer: jest.fn(),
    removeLayer: jest.fn(),
    getSource: jest.fn(),
    getLayer: jest.fn(),
    flyTo: jest.fn(),
    easeTo: jest.fn(),
    jumpTo: jest.fn(),
    setCenter: jest.fn(),
    setZoom: jest.fn(),
    setPitch: jest.fn(),
    setBearing: jest.fn(),
    getCenter: jest.fn().mockReturnValue({ lat: 9.082, lng: 7.49 }),
    getZoom: jest.fn().mockReturnValue(14),
    getPitch: jest.fn().mockReturnValue(60),
    getBearing: jest.fn().mockReturnValue(0),
    resize: jest.fn(),
    loaded: jest.fn().mockReturnValue(true),
    getContainer: jest.fn().mockReturnValue(document.createElement('div')),
    getCanvas: jest.fn().mockReturnValue(document.createElement('canvas')),
    project: jest.fn().mockReturnValue({ x: 0, y: 0 }),
    unproject: jest.fn().mockReturnValue({ lat: 9.082, lng: 7.49 }),
    queryRenderedFeatures: jest.fn().mockReturnValue([]),
    setLayoutProperty: jest.fn(),
    setPaintProperty: jest.fn(),
  })),
  
  Marker: jest.fn().mockImplementation(() => ({
    setLngLat: jest.fn().mockReturnThis(),
    addTo: jest.fn().mockReturnThis(),
    remove: jest.fn(),
    getElement: jest.fn().mockReturnValue(document.createElement('div')),
    setPopup: jest.fn().mockReturnThis(),
    getPopup: jest.fn(),
    togglePopup: jest.fn(),
    getLngLat: jest.fn().mockReturnValue({ lat: 9.082, lng: 7.49 }),
  })),
  
  Popup: jest.fn().mockImplementation(() => ({
    setLngLat: jest.fn().mockReturnThis(),
    setHTML: jest.fn().mockReturnThis(),
    setText: jest.fn().mockReturnThis(),
    addTo: jest.fn().mockReturnThis(),
    remove: jest.fn(),
    isOpen: jest.fn().mockReturnValue(false),
  })),
  
  NavigationControl: jest.fn(),
  ScaleControl: jest.fn(),
  GeolocateControl: jest.fn().mockImplementation(() => ({
    on: jest.fn(),
    trigger: jest.fn(),
  })),
  AttributionControl: jest.fn(),
  FullscreenControl: jest.fn(),
  
  LngLat: jest.fn().mockImplementation((lng, lat) => ({ lng, lat })),
  LngLatBounds: jest.fn().mockImplementation(() => ({
    extend: jest.fn().mockReturnThis(),
    getCenter: jest.fn().mockReturnValue({ lat: 9.082, lng: 7.49 }),
    getNorth: jest.fn().mockReturnValue(9.1),
    getSouth: jest.fn().mockReturnValue(9.0),
    getEast: jest.fn().mockReturnValue(7.5),
    getWest: jest.fn().mockReturnValue(7.4),
  })),
  
  supported: jest.fn().mockReturnValue(true),
  version: '4.0.0',
};

module.exports = maplibreGl;
